### ISSUE TITLE
Q17: implications of `priority[c]=1`

### ISSUE THREAD

**Issue by sophiaIC** [Theodus/backpressure-model#1]
Is there some invariant for when the priority of a cown is 1?

**Comment by sophiaIC** [comment]
eg.        prio[c]=1 --> Acquired(c)?

**Comment by Theodus** [comment]
One invariant is that `\A c \in Cowns: (priority[c] = 1) => (scheduled[c] \/ Acquired(c))`

**Comment by sophiaIC** [comment]
That is a very nice invariant to have.
>   `\A c \in Cowns: (priority[c] = 1) => (scheduled[c] \/ Acquired(c))`

Note, that it is an implication of `UnscheduledByMuteOrAcquire`.

Namely:
`UnscheduledByMuteOrAcquire`
is defined as
.       `     NOT(priority[c]=-1 \/ Acquired(c) ) <=> scheduled[c]`
and the above implies
 .      `     priority[c]>= 0   =>   ( scheduled[c] \/  Acquired(c)   ) `

**Comment by sophiaIC** [comment]
But it is not enough, as it does not preclude
```Conf_17
        queue[c2] = {​​​​​​​​​c2}​​​​​​​​   sch[c2]=false   prio[c2]=-1   mute[c2]={​​​​​​​​ }​​​​​​​​​   
​        queue[c3] = {​​​​​​​​ }​​​​​​​    sch[c3]=true    prio[c3]=1    mute[c3]={c2}

**Comment by Theodus** [comment]
With the changes I just made in https://github.com/Theodus/backpressure-model/commit/f530b1b4f92c4991d0bc9ae1be9b54c1a3043010, I've added the following invariants:
```
HighPriorityScheduledOrAcquired ==
  \A c \in Cowns: (priority[c] = 1) => (scheduled[c] \/ Acquired(c))

HighPriorityInQueue ==
  \A c \in Cowns: (priority[c] = 1) =>
    \E k \in Cowns: c \in UNION Range(queue[k])

Required(c) == \E k \in Cowns: (k < c) /\ (c \in UNION Range(queue[k]))
SleepingIsNormalOrRequired ==
  \A c \in Cowns: Sleeping(c) => ((priority[c] = 0) \/ Required(c))
```

**Comment by sophiaIC** [comment]
I suggest you remove `HighPriorityScheduledOrAcquired`, because as I said in issue Q16, int is a consequence of `UnscheduledByMuteOrAcquire`.

**Comment by sophiaIC** [comment]
I like the other two.

**Comment by sophiaIC** [comment]
Can `HighPriorityInQueue` be strengthened to become

```HighPriorityInQueue ==
  \A c \in Cowns: (priority[c] = 1) =>
    \E k \in Cowns: ( c \in UNION Range(queue[k]) /\ c < k )

**Comment by Theodus** [comment]
> Can `HighPriorityInQueue` be strengthened to become
> 
> ```
>   \A c \in Cowns: (priority[c] = 1) =>
>     \E k \in Cowns: ( c \in UNION Range(queue[k]) /\ c < k )
> ```

No, `k` can be greater than, less than, or equal to `c`

**Comment by sophiaIC** [comment]
OK, then I think this is it, and we can close that issue as well.
