### ISSUE TITLE
What happened to  `WillScheduleCown`

### ISSUE THREAD

**Issue by sophiaIC** [Theodus/backpressure-model#14]
In the last there was an invariant, called `WillScheduleCown` which puzzled me. Will we drop it? I will be glad it f we do so. Attached the definition
![image](https://user-images.githubusercontent.com/6861169/97848222-aae42180-1ce8-11eb-8956-c2a4faec1384.png)

**Comment by Theodus** [comment]
`WillScheduleCown` was removed in https://github.com/Theodus/backpressure-model/commit/42ff703cdf3b9ff5555eef7a82013ca563fad6e9. I agree that it should be removed unless something like it is deemed necessary in the future
