### ISSUE TITLE
Q19: requiring weaker definition of Terminated

### ISSUE THREAD

**Issue by sophiaIC** [Theodus/backpressure-model#5]
I want to propose that we make the definition of  terminated slightly weaker, and propose that it should be
     `Terminated_Weak ≜  \forall c. [ queue[c]=\empty ]`

The reason for my proposal is that the negation of `Terminated` as defined now is too weak. Namely,  `Terminated` is stronger than `Terminated_Weak`, and is defined as 
     `Terminated   ≜  \forall c. [ queue[c]=\empty /\  scheduled[c] ]`
The negation of `Terminated` is 
                                   ` \exists c. [ queue[c]=/=\empty \/ NOT( scheduled[c] ) ]`
which is too weak, because it considers a configuration which has  a cown that has not been scheduled as not terminated, and this is too weak.

I believe that "not terminated" should just be
                                   ` \exists c. [ queue[c]=/=\empty ]`  

In fact, using the negation of `Terminated` as defined now in the proof of deadlock freedom is not useful.

**Comment by Theodus** [comment]
That makes sense. I've updated the `Terminating` step as follows in https://github.com/Theodus/backpressure-model/commit/4d849b4a22534d5a39c01c7df3eeb42845538776:
```
Terminating ==
  /\ \A c \in Cowns: Len(queue[c]) = 0
  /\ Assert(\A c \in Cowns: Sleeping(c), "Termination with unscheduled cowns")
  /\ UNCHANGED vars
```

**Comment by sophiaIC** [comment]
But you still have the `Termination` PROPERTY, which, I think makes tmodel checking very slow. Probably I misunderstand something...
